### ISSUE TITLE
A error occurred :(

### ISSUE THREAD

**Issue by turunut** [bahamapascal/CL-Wallet#21]
Hello, I would like to modify your wallet to generate transfers from a security level 3 address but first I have tried to send a iota from a normal level 2 address without modifing the code and I get a message at the end of the proces:

Okay, sending transfer(s) now. This can take a while...
Sending transfer, this can take a while...
A error occurred :(

I'm using the host: https://potato.iotasalad.org:14265
windows 10, python 3.6.2

**Comment by bahamapascal** [comment]
Hi turunut, glad to see some one using the wallet even though it isn't released yet :)
I would assume that it is something with your host you are connecting to (does it have PoW enabled?)
Please try with my host: http://bahamapascal1.ddns.net:33333
If that doesn't solve it we can see further.

Cheers

**Comment by turunut** [comment]
Wow thanks! This works.
Ok I have done a normal transaccion but looking your code I see that you don't use de API Pyota to generate the addresses (api.get_new_addresses(...)). You use "generator.get_addresses(start_index, count)" and I don't know how to generate security level 3 addresses with that.
So I have used the pyota API insteed and generated a transaction.
```
        api = Iota(iotaNode, seed)
        gna_result = api.get_new_addresses( count=1, security_level = 3)
        addresses = gna_result['addresses']
```
The Wallet have generated the transaction and send it but I'm not completly sure if this will work.
Here is the level 3 wallet from whom I sent the iota.
https://iotasear.ch/address/EJFUUMITGPQPN9JCKXNWTDVKFTJGVHSLONKFTBKOHQLLUGGUDOHLIK9YQLQZMQUISWFS9VTQGCANUWWS9JYCQNYGFB
(I'm reataching it every 20min... but I don't know if this will eventually work)

If this works its a very easy implementation and as far as I know your wallet would be the only one capable of doing this kind of transaction. With this you could gain a lot of users.

**Comment by turunut** [comment]
Yes it works :) I will post the modifications in a fork but is very rudimentary.

**Comment by bahamapascal** [comment]
Sounds good :)
Will maybe add the security_level to the account settings in the future
Any ways, I will close this issue now as it is solved
