### ISSUE TITLE
"A error occurred :-(" when trying to send transfer

### ISSUE THREAD

**Issue by huggre** [bahamapascal/CL-Wallet#23]
Hi
Im currently testing your great CL Python wallet and everything works fine until i try to send funds.
After entering "confirm" an error message is returned "A error occurred :-("
Any idea what might be wrong? I really would like this to work.

Note! Im using my own full node and have no problems when using the standard IOTA Wallet.

**Comment by turunut** [comment]
I had the same problem. You can find it on Closed issues.
Here the answer by bahamapascal:

> Hi turunut, glad to see some one using the wallet even though it isn't released yet :)
> I would assume that it is something with your host you are connecting to (does it have PoW enabled?)
> Please try with my host: http://bahamapascal1.ddns.net:33333
> If that doesn't solve it we can see further.
> 
> Cheers

If you connect to their host it works great.
Good luck!

**Comment by huggre** [comment]
Thats it, just had to enable AttachToTangle on my node and now its working, thanks

**Comment by bahamapascal** [comment]
Thanks @turunut for your support!
By the way, there was quite a bit of work done in the background: https://github.com/bahamapascal/CL-Wallet/pull/24
So a new version will be coming soon(tm) :)

I will close this issue now as it's solved
